"use client";

import {
  fmt,
  fmtDate,
  getInvTotal,
  clientName,
  type Invoice,
} from "@/types/admin";

interface Props {
  invoice: Invoice;
  onClose: () => void;
}

export default function InvoicePreview({ invoice, onClose }: Props) {
  const { sub, tax, total } = getInvTotal(invoice);

  const handlePrint = () => window.print();

  return (
    <div>
      <div className="preview-select-bar no-print">
        <button className="btn-ghost" onClick={onClose}>
          ← Back
        </button>
        <div>
          <button className="btn-primary" onClick={handlePrint}>
            Print / Download PDF
          </button>
        </div>
      </div>

      <div className="inv-doc" id="invoice-doc">
        <div className="inv-header">
          <div>
            <div className="inv-logo">HelpDeskXpert</div>
            <div className="inv-company-info">
              123 Business Avenue, Suite 456
              <br />
              New York, NY 10001 | (555) 123-4567
              <br />
              billing@helpdeskexpert.com
            </div>
          </div>
          <div className="inv-title">
            <h2>INVOICE</h2>
            <div className="inv-meta-grid">
              <span>Invoice No:</span>
              <strong>{invoice.num}</strong>
              <span>Date:</span>
              <strong>{fmtDate(invoice.issued)}</strong>
              <span>Due:</span>
              <strong>{fmtDate(invoice.due)}</strong>
              <span>Status:</span>
              <strong className={`inv-status-${invoice.status.toLowerCase()}`}>
                {invoice.status}
              </strong>
            </div>
          </div>
        </div>

        <div className="inv-bill-to">
          <h4>Bill To</h4>
          <div className="inv-client-name">{clientName(invoice.client)}</div>
          {invoice.client.company && <div>{invoice.client.company}</div>}
          <div>{invoice.client.email}</div>
          {invoice.client.phone && <div>{invoice.client.phone}</div>}
        </div>

        <table className="inv-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Description</th>
              <th>Qty</th>
              <th>Unit Price</th>
              <th style={{ textAlign: "right" }}>Amount</th>
            </tr>
          </thead>
          <tbody>
            {invoice.items.map((li, i) => (
              <tr key={i}>
                <td>{i + 1}</td>
                <td>{li.desc}</td>
                <td>{li.qty}</td>
                <td>{fmt(li.price)}</td>
                <td style={{ textAlign: "right" }}>{fmt(li.qty * li.price)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="inv-totals">
          <div className="inv-total-row">
            <span>Subtotal</span>
            <span>{fmt(sub)}</span>
          </div>
          <div className="inv-total-row">
            <span>Tax ({invoice.tax}%)</span>
            <span>{fmt(tax)}</span>
          </div>
          <div className="inv-total-row inv-grand-total">
            <span>Total Due</span>
            <span>{fmt(total)}</span>
          </div>
        </div>

        {invoice.bank && (
          <div className="inv-bank">
            <h4>Payment Details</h4>
            <p style={{ whiteSpace: "pre-wrap" }}>{invoice.bank}</p>
          </div>
        )}

        {invoice.notes && (
          <div className="inv-notes">
            <h4>Notes</h4>
            <p>{invoice.notes}</p>
          </div>
        )}

        <div className="inv-footer">
          Thank you for your business!
          <br />
          <small>
            This invoice was generated by HelpDeskXpert invoice system.
          </small>
        </div>
      </div>
    </div>
  );
}
